import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'dart:typed_data';
import '../theme.dart';
import '../services/database_service.dart';
import '../services/storage_service.dart';
import '../services/auth_service.dart';
import 'package:provider/provider.dart';

class UploadScreen extends StatefulWidget {
  final String? initialFolderId;

  const UploadScreen({
    super.key,
    this.initialFolderId,
  });

  @override
  State<UploadScreen> createState() => _UploadScreenState();
}

class _UploadScreenState extends State<UploadScreen> {
  int _currentStep = 0;
  String? _selectedFileName;
  Uint8List? _selectedFileBytes;
  final _titleController = TextEditingController();
  bool _isUploading = false;

  // Folder state
  List<FolderModel> _folders = [];
  FolderModel? _selectedFolder;
  bool _loadingFolders = true;

  final DatabaseService _databaseService = DatabaseService();
  final StorageService _storageService = StorageService();

  @override
  void initState() {
    super.initState();
    _loadFolders();
  }

  Future<void> _loadFolders() async {
    try {
      final folders = await _databaseService.getAllFolders();
      setState(() {
        // To allow uploading to Root, insert a dummy folder model or handle nulls
        _folders = folders;
        _folders.insert(
            0, FolderModel(id: 'root', name: 'Root', parentId: null));
        _loadingFolders = false;
        if (_folders.isNotEmpty) {
          if (widget.initialFolderId != null) {
            try {
              _selectedFolder =
                  _folders.firstWhere((f) => f.id == widget.initialFolderId);
            } catch (_) {
              _selectedFolder = _folders.first;
            }
          } else {
            _selectedFolder = _folders.first;
          }
        }
      });
    } catch (e) {
      if (mounted) setState(() => _loadingFolders = false);
      debugPrint('Error loading folders: $e');
    }
  }

  Future<void> _pickFile() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.any,
      withData: true,
    );

    if (result != null && result.files.isNotEmpty) {
      final file = result.files.first;
      setState(() {
        _selectedFileName = file.name;
        _selectedFileBytes = file.bytes;
      });
    }
  }

  Future<void> _performUpload() async {
    if (_selectedFileBytes == null || _selectedFileName == null) {
      _showSnackBar('Please select a file first.', isError: true);
      return;
    }
    if (_selectedFolder == null) {
      _showSnackBar('Please select a folder.', isError: true);
      return;
    }

    final authService = Provider.of<AuthService>(context, listen: false);
    setState(() => _isUploading = true);

    try {
      // 1. Upload file to Storage
      final fileUrl = await _storageService.uploadDocument(
        _selectedFileBytes!,
        _selectedFileName!,
      );

      if (fileUrl == null) {
        throw Exception('File upload failed');
      }

      // 2. Get current user ID
      final userId = authService.currentUser?.id ?? '';

      // 3. Save document metadata to database
      String? targetFolderId =
          _selectedFolder!.id == 'root' ? null : _selectedFolder!.id;

      final doc = DocumentModel(
        id: '', // Auto-generated by Supabase
        title: _titleController.text.isEmpty
            ? _selectedFileName!
            : _titleController.text,
        folderId: targetFolderId,
        uploadedBy: userId,
        uploadDate: DateTime.now(),
        fileUrl: fileUrl,
      );

      await _databaseService.saveDocumentMetadata(doc);

      if (mounted) {
        _showSnackBar('Document uploaded successfully! 🎉');
        Navigator.pop(context, true);
      }
    } catch (e) {
      debugPrint('Upload error: $e');
      if (mounted) {
        _showSnackBar('Upload failed: ${e.toString()}', isError: true);
      }
    } finally {
      if (mounted) {
        setState(() => _isUploading = false);
      }
    }
  }

  void _showSnackBar(String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        behavior: SnackBarBehavior.floating,
        backgroundColor: isError ? Colors.redAccent : AnweshanTheme.primaryDeep,
        margin: const EdgeInsets.only(
          top: 20,
          left: 24,
          right: 24,
        ),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        duration: const Duration(seconds: 3),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Scaffold(
          appBar: AppBar(
            title: const Text('Upload Document'),
            leading: IconButton(
              icon: const Icon(Icons.close),
              onPressed: _isUploading ? null : () => Navigator.pop(context),
            ),
          ),
          body: Stepper(
            type: StepperType.horizontal,
            currentStep: _currentStep,
            onStepContinue: () {
              if (_currentStep < 2) {
                // Validate before moving forward
                if (_currentStep == 0 && _selectedFileBytes == null) {
                  _showSnackBar('Please select a file first.', isError: true);
                  return;
                }
                setState(() => _currentStep++);
              } else {
                // Final step — perform upload
                _performUpload();
              }
            },
            onStepCancel: () {
              if (_currentStep > 0) setState(() => _currentStep--);
            },
            controlsBuilder: (BuildContext context, ControlsDetails details) {
              final isLastStep = _currentStep == 2;
              final canContinue = isLastStep
                  ? (_selectedFileBytes != null && _selectedFolder != null)
                  : (_currentStep == 0 ? _selectedFileBytes != null : true);

              return Padding(
                padding: const EdgeInsets.only(top: 20),
                child: Row(
                  children: [
                    ElevatedButton(
                      onPressed: canContinue ? details.onStepContinue : null,
                      child: Text(isLastStep ? 'Upload' : 'Continue'),
                    ),
                    const SizedBox(width: 12),
                    if (_currentStep > 0)
                      TextButton(
                        onPressed: details.onStepCancel,
                        child: const Text('Back',
                            style: TextStyle(color: AnweshanTheme.primaryDeep)),
                      ),
                  ],
                ),
              );
            },
            steps: [
              Step(
                title: const Text('File'),
                isActive: _currentStep >= 0,
                content: _buildFileStep(),
              ),
              Step(
                title: const Text('Details'),
                isActive: _currentStep >= 1,
                content: _buildDetailsStep(),
              ),
              Step(
                title: const Text('Confirm'),
                isActive: _currentStep >= 2,
                content: _buildConfirmStep(),
              ),
            ],
          ),
        ),
        // Loading overlay
        if (_isUploading)
          Container(
            color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.5),
            child: const Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  CircularProgressIndicator(color: AnweshanTheme.secondaryGold),
                  SizedBox(height: 20),
                  Text(
                    'Uploading document...',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildFileStep() {
    return Column(
      children: [
        const SizedBox(height: 40),
        Icon(Icons.cloud_upload_outlined,
            size: 80, color: AnweshanTheme.primaryDeep.withValues(alpha: 0.5)),
        const SizedBox(height: 24),
        Text('Select a document to upload',
            style: Theme.of(context)
                .textTheme
                .headlineMedium
                ?.copyWith(fontSize: 18)),
        const SizedBox(height: 8),
        Text('Supported: PDF, Images, Word, PPT (Max 20MB)',
            style: Theme.of(context).textTheme.labelLarge),
        const SizedBox(height: 32),
        ElevatedButton.icon(
          onPressed: _pickFile,
          icon: Icon(_selectedFileName != null ? Icons.edit : Icons.add),
          label: Text(_selectedFileName ?? 'Choose File'),
        ),
        if (_selectedFileName != null) ...[
          const SizedBox(height: 24),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: AnweshanTheme.secondaryGold.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                const Icon(Icons.check_circle, color: Colors.green),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(_selectedFileName!,
                          style: const TextStyle(fontWeight: FontWeight.bold)),
                      if (_selectedFileBytes != null)
                        Text(
                          '${(_selectedFileBytes!.length / 1024 / 1024).toStringAsFixed(2)} MB',
                          style: Theme.of(context).textTheme.labelLarge,
                        ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ],
    );
  }

  Widget _buildDetailsStep() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text('Document Title',
            style: TextStyle(fontWeight: FontWeight.bold)),
        const SizedBox(height: 8),
        TextField(
          controller: _titleController,
          decoration:
              const InputDecoration(hintText: 'e.g. Q4 Strategy Report'),
        ),
        const SizedBox(height: 24),
        const Text('Destination Folder',
            style: TextStyle(fontWeight: FontWeight.bold)),
        const SizedBox(height: 8),
        _loadingFolders
            ? const Center(child: CircularProgressIndicator())
            : _folders.isEmpty
                ? const Text('No folders found.',
                    style: TextStyle(color: Colors.red))
                : DropdownButtonFormField<String>(
                    initialValue: _selectedFolder?.id,
                    decoration: const InputDecoration(),
                    items: _folders.map((FolderModel cat) {
                      return DropdownMenuItem<String>(
                        value: cat.id,
                        child: Text(cat.name),
                      );
                    }).toList(),
                    onChanged: (val) {
                      if (val != null) {
                        setState(() {
                          _selectedFolder =
                              _folders.firstWhere((cat) => cat.id == val);
                        });
                      }
                    },
                  ),
      ],
    );
  }

  Widget _buildConfirmStep() {
    return Column(
      children: [
        const Icon(Icons.verified_user_outlined,
            size: 64, color: AnweshanTheme.primaryDeep),
        const SizedBox(height: 16),
        const Text('Ready to Upload',
            style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
        const SizedBox(height: 24),
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              children: [
                _buildConfirmRow(
                    'Title',
                    _titleController.text.isEmpty
                        ? (_selectedFileName ?? 'Untitled')
                        : _titleController.text),
                const Divider(),
                _buildConfirmRow('File', _selectedFileName ?? 'None'),
                const Divider(),
                _buildConfirmRow('Folder', _selectedFolder?.name ?? 'Root'),
                if (_selectedFileBytes != null) ...[
                  const Divider(),
                  _buildConfirmRow('Size',
                      '${(_selectedFileBytes!.length / 1024 / 1024).toStringAsFixed(2)} MB'),
                ],
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildConfirmRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(color: Colors.grey)),
          Flexible(
            child: Text(value,
                style: const TextStyle(fontWeight: FontWeight.bold),
                textAlign: TextAlign.end),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _titleController.dispose();
    super.dispose();
  }
}
